apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebackend
  namespace: ecommerce-ns
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nodebackend
  template:
    metadata:
      labels:
        app: nodebackend
    spec:
      containers:
      - name: nodejs
        image: cloudwithrk/nodebackend:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: ecommerce-config 
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DB_NAME
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: PORT
        resources:
          requests: 
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
