apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-ns
data: 
  MYSQL_DATABASE: ecommerce_db
  DB_HOST: mysql.ecommerce-ns.svc.cluster.local 
  NODE_ENV: production
  DB_USER: root 
  PORT: "5000"
