apiVersion: v1
kind: Service
metadata:
  name: ecommerce-svs
  namespace: ecommerce-ns
  labels:
    app: reactapp
spec:
  selector:
    app: reactapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
