apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: ecommerce-ns
spec:
  clusterIP: None 
  selector:
    app: mysql
  ports:
    - port: 3306 
      targetPort: 3306
      protocol: TCP
