apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: ecommerce-ns
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ecommerce;
    USE ecommerce;
    CREATE TABLE IF NOT EXISTS products (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      price DECIMAL(10, 2) NOT NULL,
      image_url VARCHAR(255)
    );
    INSERT INTO products (name, price, image_url)
    VALUES ('Product A', 19.99, ''), ('Product B', 29.99, '');
